# https://github.com/go-task/task

version: "3"

tasks:
  run-server:
    cmds:
      - uv run --no-dev --frozen manage.py runserver
  migrate:
    cmds:
      - uv run --no-dev --frozen manage.py migrate
  makemigrations:
    cmds:
      - uv run --no-dev --frozen manage.py makemigrations
  cleanstart:
    cmds:
      - rm -rf media
      - rm -rf data
      - mkdir media/
      - mkdir media/fullsize
      - mkdir media/thumbnails
      - mkdir data
      - mkdir data/logs
      - task: migrate
  format:
    cmds:
      - ruff format .
  check:
    cmds:
      - ruff check .
  lint:
    cmds:
      - task: format
      - task: check
      - task: format
  schema:
    cmds:
      - uv run --frozen manage.py export_openapi_schema --output schema.json --indent 2
  test:
    cmds:
      - uv run --frozen pytest
