# https://github.com/go-task/task

version: "3"

tasks:
  dev-virtualenv:
    cmds:
      - pipenv sync --dev
  typing:
    deps:
      - dev-virtualenv
    cmds:
      - mypy .
  run-server:
    deps:
      - dev-virtualenv
    cmds:
      - python manage.py runserver
  migrate:
    cmds:
      - python manage.py migrate

  makemigrations:
    cmds:
      - python manage.py makemigrations

  cleanstart:
    cmds:
      - rm -rf media
      - rm -rf data
      - mkdir media/
      - mkdir media/fullsize
      - mkdir media/thumbnails
      - mkdir data
      - mkdir data/logs
      - task: migrate

  format:
    cmds:
      - ruff format .
  check:
    cmds:
      - ruff check .
  lint:
    cmds:
      - task: format
      - task: check
      - task: format
  schema:
    cmds:
      - python manage.py export_openapi_schema --output schema.json --indent 2
