from typing import Final

from scansteward.common.iso3166.models import Subdivision

SUBDIVISIONS: Final[list[Subdivision]] = [
    Subdivision("BS-AK", "Acklins"),
    Subdivision("BS-BI", "Bimini"),
    Subdivision("BS-BP", "Black Point"),
    Subdivision("BS-BY", "Berry Islands"),
    Subdivision("BS-CE", "Central Eleuthera"),
    Subdivision("BS-CI", "Cat Island"),
    Subdivision("BS-CK", "Crooked Island and Long Cay"),
    Subdivision("BS-CO", "Central Abaco"),
    Subdivision("BS-CS", "Central Andros"),
    Subdivision("BS-EG", "East Grand Bahama"),
    Subdivision("BS-EX", "Exuma"),
    Subdivision("BS-FP", "City of Freeport"),
    Subdivision("BS-GC", "Grand Cay"),
    Subdivision("BS-HI", "Harbour Island"),
    Subdivision("BS-HT", "Hope Town"),
    Subdivision("BS-IN", "Inagua"),
    Subdivision("BS-LI", "Long Island"),
    Subdivision("BS-MC", "Mangrove Cay"),
    Subdivision("BS-MG", "Mayaguana"),
    Subdivision("BS-MI", "Moore's Island"),
    Subdivision("BS-NE", "North Eleuthera"),
    Subdivision("BS-NO", "North Abaco"),
    Subdivision("BS-NP", "New Providence"),
    Subdivision("BS-NS", "North Andros"),
    Subdivision("BS-RC", "Rum Cay"),
    Subdivision("BS-RI", "Ragged Island"),
    Subdivision("BS-SA", "South Andros"),
    Subdivision("BS-SE", "South Eleuthera"),
    Subdivision("BS-SO", "South Abaco"),
    Subdivision("BS-SS", "San Salvador"),
    Subdivision("BS-SW", "Spanish Wells"),
    Subdivision("BS-WG", "West Grand Bahama"),
]
