from typing import Final

from scansteward.common.iso3166.models import Subdivision

SUBDIVISIONS: Final[list[Subdivision]] = [
    Subdivision("GN-B", "Boké"),
    Subdivision("GN-BE", "Beyla"),
    Subdivision("GN-BF", "Boffa"),
    Subdivision("GN-BK", "Boké"),
    Subdivision("GN-C", "Conakry"),
    Subdivision("GN-CO", "Coyah"),
    Subdivision("GN-D", "Kindia"),
    Subdivision("GN-DB", "Dabola"),
    Subdivision("GN-DI", "Dinguiraye"),
    Subdivision("GN-DL", "Dalaba"),
    Subdivision("GN-DU", "Dubréka"),
    Subdivision("GN-F", "Faranah"),
    Subdivision("GN-FA", "Faranah"),
    Subdivision("GN-FO", "Forécariah"),
    Subdivision("GN-FR", "Fria"),
    Subdivision("GN-GA", "Gaoual"),
    Subdivision("GN-GU", "Guékédou"),
    Subdivision("GN-K", "Kankan"),
    Subdivision("GN-KA", "Kankan"),
    Subdivision("GN-KB", "Koubia"),
    Subdivision("GN-KD", "Kindia"),
    Subdivision("GN-KE", "Kérouané"),
    Subdivision("GN-KN", "Koundara"),
    Subdivision("GN-KO", "Kouroussa"),
    Subdivision("GN-KS", "Kissidougou"),
    Subdivision("GN-L", "Labé"),
    Subdivision("GN-LA", "Labé"),
    Subdivision("GN-LE", "Lélouma"),
    Subdivision("GN-LO", "Lola"),
    Subdivision("GN-M", "Mamou"),
    Subdivision("GN-MC", "Macenta"),
    Subdivision("GN-MD", "Mandiana"),
    Subdivision("GN-ML", "Mali"),
    Subdivision("GN-MM", "Mamou"),
    Subdivision("GN-N", "Nzérékoré"),
    Subdivision("GN-NZ", "Nzérékoré"),
    Subdivision("GN-PI", "Pita"),
    Subdivision("GN-SI", "Siguiri"),
    Subdivision("GN-TE", "Télimélé"),
    Subdivision("GN-TO", "Tougué"),
    Subdivision("GN-YO", "Yomou"),
]
