from typing import Final

from scansteward.common.iso3166.models import Subdivision

SUBDIVISIONS: Final[list[Subdivision]] = [
    Subdivision("IR-00", "Markazī"),
    Subdivision("IR-01", "Gīlān"),
    Subdivision("IR-02", "Māzandarān"),
    Subdivision("IR-03", "Āz̄ārbāyjān-e Shārqī"),
    Subdivision("IR-04", "Āz̄ārbāyjān-e Ghārbī"),
    Subdivision("IR-05", "Kermānshāh"),
    Subdivision("IR-06", "Khūzestān"),
    Subdivision("IR-07", "Fārs"),
    Subdivision("IR-08", "Kermān"),
    Subdivision("IR-09", "Khorāsān-e Raẕavī"),
    Subdivision("IR-10", "Eşfahān"),
    Subdivision("IR-11", "Sīstān va Balūchestān"),
    Subdivision("IR-12", "Kordestān"),
    Subdivision("IR-13", "Hamadān"),
    Subdivision("IR-14", "Chahār Maḩāl va Bakhtīārī"),
    Subdivision("IR-15", "Lorestān"),
    Subdivision("IR-16", "Īlām"),
    Subdivision("IR-17", "Kohgīlūyeh va Bowyer Aḩmad"),
    Subdivision("IR-18", "Būshehr"),
    Subdivision("IR-19", "Zanjān"),
    Subdivision("IR-20", "Semnān"),
    Subdivision("IR-21", "Yazd"),
    Subdivision("IR-22", "Hormozgān"),
    Subdivision("IR-23", "Tehrān"),
    Subdivision("IR-24", "Ardabīl"),
    Subdivision("IR-25", "Qom"),
    Subdivision("IR-26", "Qazvīn"),
    Subdivision("IR-27", "Golestān"),
    Subdivision("IR-28", "Khorāsān-e Shomālī"),
    Subdivision("IR-29", "Khorāsān-e Jonūbī"),
    Subdivision("IR-30", "Alborz"),
]
