from typing import Final

from scansteward.common.iso3166.models import Subdivision

SUBDIVISIONS: Final[list[Subdivision]] = [
    Subdivision("MD-AN", "Anenii Noi"),
    Subdivision("MD-BA", "Bălți"),
    Subdivision("MD-BD", "Bender [Tighina]"),
    Subdivision("MD-BR", "Briceni"),
    Subdivision("MD-BS", "Basarabeasca"),
    Subdivision("MD-CA", "Cahul"),
    Subdivision("MD-CL", "Călărași"),
    Subdivision("MD-CM", "Cimișlia"),
    Subdivision("MD-CR", "Criuleni"),
    Subdivision("MD-CS", "Căușeni"),
    Subdivision("MD-CT", "Cantemir"),
    Subdivision("MD-CU", "Chișinău"),
    Subdivision("MD-DO", "Dondușeni"),
    Subdivision("MD-DR", "Drochia"),
    Subdivision("MD-DU", "Dubăsari"),
    Subdivision("MD-ED", "Edineț"),
    Subdivision("MD-FA", "Fălești"),
    Subdivision("MD-FL", "Florești"),
    Subdivision("MD-GA", "Găgăuzia, Unitatea teritorială autonomă (UTAG)"),
    Subdivision("MD-GL", "Glodeni"),
    Subdivision("MD-HI", "Hîncești"),
    Subdivision("MD-IA", "Ialoveni"),
    Subdivision("MD-LE", "Leova"),
    Subdivision("MD-NI", "Nisporeni"),
    Subdivision("MD-OC", "Ocnița"),
    Subdivision("MD-OR", "Orhei"),
    Subdivision("MD-RE", "Rezina"),
    Subdivision("MD-RI", "Rîșcani"),
    Subdivision("MD-SD", "Șoldănești"),
    Subdivision("MD-SI", "Sîngerei"),
    Subdivision("MD-SN", "Stînga Nistrului, unitatea teritorială din"),
    Subdivision("MD-SO", "Soroca"),
    Subdivision("MD-ST", "Strășeni"),
    Subdivision("MD-SV", "Ștefan Vodă"),
    Subdivision("MD-TA", "Taraclia"),
    Subdivision("MD-TE", "Telenești"),
    Subdivision("MD-UN", "Ungheni"),
]
