from typing import Final

from scansteward.common.iso3166.models import Subdivision

SUBDIVISIONS: Final[list[Subdivision]] = [
    Subdivision("MW-BA", "Balaka"),
    Subdivision("MW-BL", "Blantyre"),
    Subdivision("MW-C", "Central Region"),
    Subdivision("MW-CK", "Chikwawa"),
    Subdivision("MW-CR", "Chiradzulu"),
    Subdivision("MW-CT", "Chitipa"),
    Subdivision("MW-DE", "Dedza"),
    Subdivision("MW-DO", "Dowa"),
    Subdivision("MW-KR", "Karonga"),
    Subdivision("MW-KS", "Kasungu"),
    Subdivision("MW-LI", "Lilongwe"),
    Subdivision("MW-LK", "Likoma"),
    Subdivision("MW-MC", "Mchinji"),
    Subdivision("MW-MG", "Mangochi"),
    Subdivision("MW-MH", "Machinga"),
    Subdivision("MW-MU", "Mulanje"),
    Subdivision("MW-MW", "Mwanza"),
    Subdivision("MW-MZ", "Mzimba"),
    Subdivision("MW-N", "Northern Region"),
    Subdivision("MW-NB", "Nkhata Bay"),
    Subdivision("MW-NE", "Neno"),
    Subdivision("MW-NI", "Ntchisi"),
    Subdivision("MW-NK", "Nkhotakota"),
    Subdivision("MW-NS", "Nsanje"),
    Subdivision("MW-NU", "Ntcheu"),
    Subdivision("MW-PH", "Phalombe"),
    Subdivision("MW-RU", "Rumphi"),
    Subdivision("MW-S", "Southern Region"),
    Subdivision("MW-SA", "Salima"),
    Subdivision("MW-TH", "Thyolo"),
    Subdivision("MW-ZO", "Zomba"),
]
