from typing import Final

from scansteward.common.iso3166.models import Subdivision

SUBDIVISIONS: Final[list[Subdivision]] = [
    Subdivision("RO-AB", "Alba"),
    Subdivision("RO-AG", "Argeș"),
    Subdivision("RO-AR", "Arad"),
    Subdivision("RO-B", "București"),
    Subdivision("RO-BC", "Bacău"),
    Subdivision("RO-BH", "Bihor"),
    Subdivision("RO-BN", "Bistrița-Năsăud"),
    Subdivision("RO-BR", "Brăila"),
    Subdivision("RO-BT", "Botoșani"),
    Subdivision("RO-BV", "Brașov"),
    Subdivision("RO-BZ", "Buzău"),
    Subdivision("RO-CJ", "Cluj"),
    Subdivision("RO-CL", "Călărași"),
    Subdivision("RO-CS", "Caraș-Severin"),
    Subdivision("RO-CT", "Constanța"),
    Subdivision("RO-CV", "Covasna"),
    Subdivision("RO-DB", "Dâmbovița"),
    Subdivision("RO-DJ", "Dolj"),
    Subdivision("RO-GJ", "Gorj"),
    Subdivision("RO-GL", "Galați"),
    Subdivision("RO-GR", "Giurgiu"),
    Subdivision("RO-HD", "Hunedoara"),
    Subdivision("RO-HR", "Harghita"),
    Subdivision("RO-IF", "Ilfov"),
    Subdivision("RO-IL", "Ialomița"),
    Subdivision("RO-IS", "Iași"),
    Subdivision("RO-MH", "Mehedinți"),
    Subdivision("RO-MM", "Maramureș"),
    Subdivision("RO-MS", "Mureș"),
    Subdivision("RO-NT", "Neamț"),
    Subdivision("RO-OT", "Olt"),
    Subdivision("RO-PH", "Prahova"),
    Subdivision("RO-SB", "Sibiu"),
    Subdivision("RO-SJ", "Sălaj"),
    Subdivision("RO-SM", "Satu Mare"),
    Subdivision("RO-SV", "Suceava"),
    Subdivision("RO-TL", "Tulcea"),
    Subdivision("RO-TM", "Timiș"),
    Subdivision("RO-TR", "Teleorman"),
    Subdivision("RO-VL", "Vâlcea"),
    Subdivision("RO-VN", "Vrancea"),
    Subdivision("RO-VS", "Vaslui"),
]
