from typing import Final

from scansteward.common.iso3166.models import Subdivision

SUBDIVISIONS: Final[list[Subdivision]] = [
    Subdivision("RS-00", "Beograd"),
    Subdivision("RS-01", "Severnobački okrug"),
    Subdivision("RS-02", "Srednjebanatski okrug"),
    Subdivision("RS-03", "Severnobanatski okrug"),
    Subdivision("RS-04", "Južnobanatski okrug"),
    Subdivision("RS-05", "Zapadnobački okrug"),
    Subdivision("RS-06", "Južnobački okrug"),
    Subdivision("RS-07", "Sremski okrug"),
    Subdivision("RS-08", "Mačvanski okrug"),
    Subdivision("RS-09", "Kolubarski okrug"),
    Subdivision("RS-10", "Podunavski okrug"),
    Subdivision("RS-11", "Braničevski okrug"),
    Subdivision("RS-12", "Šumadijski okrug"),
    Subdivision("RS-13", "Pomoravski okrug"),
    Subdivision("RS-14", "Borski okrug"),
    Subdivision("RS-15", "Zaječarski okrug"),
    Subdivision("RS-16", "Zlatiborski okrug"),
    Subdivision("RS-17", "Moravički okrug"),
    Subdivision("RS-18", "Raški okrug"),
    Subdivision("RS-19", "Rasinski okrug"),
    Subdivision("RS-20", "Nišavski okrug"),
    Subdivision("RS-21", "Toplički okrug"),
    Subdivision("RS-22", "Pirotski okrug"),
    Subdivision("RS-23", "Jablanički okrug"),
    Subdivision("RS-24", "Pčinjski okrug"),
    Subdivision("RS-25", "Kosovski okrug"),
    Subdivision("RS-26", "Pećki okrug"),
    Subdivision("RS-27", "Prizrenski okrug"),
    Subdivision("RS-28", "Kosovsko-Mitrovački okrug"),
    Subdivision("RS-29", "Kosovsko-Pomoravski okrug"),
    Subdivision("RS-KM", "Kosovo-Metohija"),
    Subdivision("RS-VO", "Vojvodina"),
]
