# Generated by Django 5.0.1 on 2024-01-26 19:48

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("checksum", models.CharField(max_length=64, unique=True, verbose_name="blake3 hex digest")),
                (
                    "original_path",
                    models.CharField(max_length=1024, unique=True, verbose_name="Path to the original image"),
                ),
                (
                    "webp_path",
                    models.CharField(
                        max_length=1024,
                        unique=True,
                        verbose_name="Path to the full size, but WebP mage",
                    ),
                ),
                (
                    "thumbnail_path",
                    models.CharField(max_length=1024, unique=True, verbose_name="Path to a thumbnail image"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonInImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("center_x", models.PositiveIntegerField()),
                ("center_y", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("exclude_from_training", models.BooleanField(default=False)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="images.image",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
