# Generated by Django 5.0.1 on 2024-02-05 03:41

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("image_metadata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "checksum",
                    models.CharField(
                        help_text="The BLAKE3 checksum of the original file",
                        max_length=64,
                        unique=True,
                        verbose_name="blake3 hex digest",
                    ),
                ),
                (
                    "original_path",
                    models.CharField(max_length=1024, unique=True, verbose_name="Path to the original image"),
                ),
                (
                    "webp_path",
                    models.CharField(
                        max_length=1024,
                        unique=True,
                        verbose_name="full size WebP of the original",
                    ),
                ),
                (
                    "thumbnail_path",
                    models.CharField(max_length=1024, unique=True, verbose_name="thumbnail image in WebP"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonInImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("center_x", models.PositiveIntegerField()),
                ("center_y", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("exclude_from_training", models.BooleanField(default=False)),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Person is in this Image at the given location",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="images.image",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person is in this Image at the given location",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="image_metadata.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="image",
            name="people",
            field=models.ManyToManyField(
                related_name="image",
                through="images.PersonInImage",
                to="image_metadata.person",
            ),
        ),
    ]
